import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Search, Download, Eye, Play, Calendar } from "lucide-react";
import { predefinedReportsData, reportHistoryData } from "@/data/reportingMockData";

const PredefinedReports = () => {
  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-3xl font-bold mb-2">Predefined Admin Reports</h1>
        <p className="text-muted-foreground">
          Access standard reports for audit activities and compliance.
        </p>
      </div>

      {/* Stats Overview */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <Card className="p-6">
          <div className="text-sm text-muted-foreground mb-2">Total Reports</div>
          <div className="text-3xl font-bold">24</div>
        </Card>
        <Card className="p-6">
          <div className="text-sm text-muted-foreground mb-2">Generated Today</div>
          <div className="text-3xl font-bold">8</div>
        </Card>
        <Card className="p-6">
          <div className="text-sm text-muted-foreground mb-2">Most Popular</div>
          <div className="text-2xl font-bold">Audit Summary</div>
        </Card>
        <Card className="p-6">
          <div className="text-sm text-muted-foreground mb-2">Last Updated</div>
          <div className="text-2xl font-bold">Today</div>
        </Card>
      </div>

      {/* Filters */}
      <Card className="p-6">
        <div className="flex flex-wrap gap-4 mb-6">
          <div className="relative flex-1 min-w-[250px]">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
            <Input placeholder="Search reports..." className="pl-10" />
          </div>
          <Select defaultValue="all">
            <SelectTrigger className="w-[200px]">
              <SelectValue placeholder="Select category" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All Categories</SelectItem>
              <SelectItem value="audit">Audit Reports</SelectItem>
              <SelectItem value="compliance">Compliance Reports</SelectItem>
              <SelectItem value="user">User Reports</SelectItem>
              <SelectItem value="system">System Reports</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <h3 className="text-xl font-semibold mb-4">Available Reports</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {predefinedReportsData.map((report) => (
            <Card key={report.id} className="p-6 hover:shadow-lg transition-shadow">
              <h4 className="font-semibold mb-2">{report.name}</h4>
              <p className="text-sm text-muted-foreground mb-3">
                {report.description}
              </p>
              <div className="text-sm text-muted-foreground mb-1">
                <strong>Last Generated:</strong> {report.lastGenerated}
              </div>
              <div className="text-sm text-muted-foreground mb-4">
                <strong>Format:</strong> {report.formats}
              </div>
              <div className="flex gap-2">
                <Button size="sm" className="flex-1">
                  <Play className="h-3 w-3 mr-1" />
                  Generate
                </Button>
                <Button size="sm" variant="outline" className="flex-1">
                  <Calendar className="h-3 w-3 mr-1" />
                  Schedule
                </Button>
              </div>
            </Card>
          ))}
        </div>
      </Card>

      {/* Report Generation History */}
      <Card className="p-6">
        <h3 className="text-xl font-semibold mb-4">Report Generation History</h3>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Report Name</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Generated Date</TableHead>
              <TableHead>Format</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {reportHistoryData.map((report) => (
              <TableRow key={report.id}>
                <TableCell className="font-medium">{report.reportName}</TableCell>
                <TableCell>{report.generatedBy}</TableCell>
                <TableCell>{report.generatedDate}</TableCell>
                <TableCell>{report.format}</TableCell>
                <TableCell>
                  <Badge
                    variant={report.status === "Completed" ? "default" : "destructive"}
                  >
                    {report.status}
                  </Badge>
                </TableCell>
                <TableCell>
                  <div className="flex gap-2">
                    {report.status === "Completed" ? (
                      <>
                        <Button size="sm" variant="outline">
                          <Download className="h-3 w-3 mr-1" />
                          Download
                        </Button>
                        <Button size="sm" variant="outline">
                          <Eye className="h-3 w-3 mr-1" />
                          View
                        </Button>
                      </>
                    ) : (
                      <>
                        <Button size="sm" variant="outline">
                          Retry
                        </Button>
                        <Button size="sm" variant="outline">
                          Details
                        </Button>
                      </>
                    )}
                  </div>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </Card>
    </div>
  );
};

export default PredefinedReports;
